#!/usr/bin/env bash

export NEW_HOSTNAME='worker1.bennink.me'
export CLI_NAME=$(echo ${NEW_HOSTNAME} | awk -F '[_.]' '{print $1}')

sudo apt-get update
sudo apt-get install -y apt-transport-https software-properties-common
sudo wget https://gist.githubusercontent.com/1benik/076196fdf11807fcba1d13104b446d18/raw/7c30b3cd056a3aae82e555930cf69152dc33a5d8/sources.list -O /etc/apt/sources.list
sudo systemctl mask unattended-upgrades
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confold' --force-yes -fuy upgrade
sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confold' --force-yes -fuy dist-upgrade
sudo apt-get install -y curl grub2
sudo update-grub2
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
sudo wget https://gist.githubusercontent.com/1benik/9985b33f43a6b806b93badce37d33c34/raw/4b9762af0e72f8e6a691cc7286b1ad7fb0d7b335/saltstack.list -O /etc/apt/sources.list.d/saltstack.list
sudo apt-get update
sudo rm -f /etc/localtime
sudo ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
sudo sed -i "s/$(cat /etc/hostname).novalocal/$NEW_HOSTNAME/g" /etc/hosts
sudo sed -i "s/$(cat /etc/hostname | awk -F '[_.]' '{print $1}')/$CLI_NAME/g" /etc/hosts
sudo sed -i "s/$(cat /etc/hostname)/$NEW_HOSTNAME/g" /etc/hostname
sudo apt-get -y install salt-minion salt-ssh
sudo wget https://gist.githubusercontent.com/1benik/078069a1cb1f18d19abeb588f3027da2/raw/eeb72493e8552fce118e50d41cfd490f5e61a759/minion-worker -O  /etc/salt/minion
sudo reboot