#!/usr/bin/env bash

sudo wget https://gist.githubusercontent.com/1benik/887138d49357e3265b5eee028957952a/raw/5f6bf1c4b2cffdb67c4451308862cb27d9cd9b84/central-init.sh -O /etc/init.d/central-init.sh
chmod +x /etc/init.d/central-init.sh
sudo /etc/init.d/central-init.sh